apiVersion: 1
datasources:
- name: Loki
  type: loki
  url: http://loki:3100
  isDefault: true
  uid: loki
- name: Tempo
  type: tempo
  url: http://tempo:3200
  uid: tempo
  nodeGraph:
    enabled: true
  search:
    hide: false
  lokiSearch:
    datasourceUid: 'loki'