version: '3'
services:
    app:
        build:
            dockerfile: docker/Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        volumes:
          - .:/var/www/html
        ports:
          - "80:8000"
        networks:
          - opentelemetry

    # To eventually offload to Tempo...
    tempo:
      image: grafana/tempo:latest
      command: [ "-config.file=/etc/tempo.yaml" ]
      volumes:
        - ./tempo/tempo.yaml:/etc/tempo.yaml
      ports:
        - "14268"  # jaeger ingest
        - "3200:3200"   # tempo
        - "4317"  # otlp grpc
        - "4318"  # otlp http
      networks:
          - opentelemetry

    collector:
        image: otel/opentelemetry-collector-contrib
        command: [ "--config=/etc/otel-collector-config.yml" ]
        volumes:
            - ./src/otelcollector/otelcol-config.yml:/etc/otel-collector-config.yml
        ports:
            - "1888:1888"   # pprof extension
            - "8888:8888"   # Prometheus metrics exposed by the collector
            - "8889:8889"   # Prometheus exporter metrics
            - "13133:13133" # health_check extension
            - "9411"   # Zipkin receiver
            - "4317:4317"        # OTLP gRPC receiver
            - "4318:4318" # OTLP/HTTP receiver
            - "55680:55679" # zpages extension
        networks:
            - opentelemetry


    grafana:
      image: grafana/grafana:9.4.3
      environment:
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        - GF_AUTH_DISABLE_LOGIN_FORM=true
        - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
      ports:
        - "3000:3000"
      networks:
          - opentelemetry

networks:
  opentelemetry:

volumes:
    db_data:
