version: '3'
services:
    app:
        build:
            dockerfile: docker/Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        volumes:
          - .:/var/www/html
        ports:
          - "80:8000"
        depends_on:
          - database
        networks:
          - opentelemetry

    database:
        image: mysql:8.0
        container_name: laravel-db
        restart: unless-stopped
        environment:
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel_user
          MYSQL_PASSWORD: your_password
          MYSQL_ROOT_PASSWORD: your_root_password
        volumes:
          - db_data:/var/lib/mysql
        networks:
          - opentelemetry

    zipkin:
        image: openzipkin/zipkin
        ports:
          - "9411:9411"
        networks:
          - opentelemetry

    jaeger:
        image: jaegertracing/all-in-one
        environment:
            COLLECTOR_ZIPKIN_HOST_PORT: 9412
        ports:
            - "9412:9412"
            - "16686:16686"
        networks:
            - opentelemetry

networks:
  opentelemetry:

volumes:
    db_data:
