version: '3'
services:
    # Fleuntbit
    fluentbit:
      container_name: fluentbit
      image: fluent/fluent-bit
      volumes:
        - ./src/fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      ports:
        - "24224:24224"
        - "24224:24224/udp"
      networks:
          - opentelemetry

    app:
        build:
            dockerfile: docker/Dockerfile
        container_name: laravel-app
        volumes:
          - .:/var/www/html
        ports:
          - "80:8000"
        networks:
          - opentelemetry
        depends_on:
          - fluentbit
        logging:
          driver: fluentd
          options:
            fluentd-address: 127.0.0.1:24224
            tag: app

    # To eventually offload to Tempo...
    tempo:
      image: grafana/tempo:latest
      command: [ "-config.file=/etc/tempo.yaml" ]
      volumes:
        - ./tempo/tempo.yaml:/etc/tempo.yaml
      ports:
        - "14268"  # jaeger ingest
        - "3200:3200"   # tempo
        - "4317"  # otlp grpc
        - "4318"  # otlp http
      networks:
          - opentelemetry

    loki:
      image: grafana/loki
      ports:
        - "3100:3100"
      command: -config.file=/etc/loki/local-config.yaml
      networks:
          - opentelemetry


    collector:
        image: otel/opentelemetry-collector-contrib
        command: [ "--config=/etc/otel-collector-config.yml" ]
        volumes:
            - ./src/otelcollector/otelcol-config.yml:/etc/otel-collector-config.yml
        ports:
            - "1888:1888"   # pprof extension
            - "8888:8888"   # Prometheus metrics exposed by the collector
            - "8889:8889"   # Prometheus exporter metrics
            - "13133:13133" # health_check extension
            - "9411"   # Zipkin receiver
            - "4317:4317"        # OTLP gRPC receiver
            - "4318:4318" # OTLP/HTTP receiver
            - "55680:55679" # zpages extension
        networks:
            - opentelemetry


    grafana:
      image: grafana/grafana:9.4.3
      environment:
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        - GF_AUTH_DISABLE_LOGIN_FORM=true
        - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
      ports:
        - "3000:3000"
      networks:
          - opentelemetry

    mysql:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel
networks:
  opentelemetry:

volumes:
    db_data:
