version: '3'
services:
    app:
        build:
            dockerfile: docker/Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        volumes:
          - .:/var/www/html
        ports:
          - "80:8000"
        depends_on:
          - database
        networks:
          - opentelemetry

    zipkin:
        image: openzipkin/zipkin
        ports:
          - "9411:9411"
        networks:
          - opentelemetry

networks:
  opentelemetry:

volumes:
    db_data:
